### ISSUE TITLE
Cannot parse double backslashes

### ISSUE THREAD

**Issue by shillingp** [MaiaVictor/nano-json-stream-parser#1]
Does not from a quick test log anything that has a double backslash.

```js
const parse = njsp(json => console.log(json))

parse('[ "\\\\" ]')
parse('[ "\\" ]')
parse(JSON.stringify(["\\"]))
```

Not sure if i am meant to escape them first, but thought it could be useful to let it be known. I understand it has no test yet and is on initial commit.

**Comment by VictorTaelin** [comment]
Thanks!
